package com.kado.app.ui.theme

import androidx.compose.ui.graphics.Color

// Primary: #FA9442 (warm orange)
val primaryLight = Color(0xFFFA9442)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDCC2)
val onPrimaryContainerLight = Color(0xFF522300)
val secondaryLight = Color(0xFFAD8971)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDCC8)
val onSecondaryContainerLight = Color(0xFF3E2318)
val tertiaryLight = Color(0xFF91945E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE3E6AA)
val onTertiaryContainerLight = Color(0xFF2B2E0B)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F4)
val onBackgroundLight = Color(0xFF211A14)
val surfaceLight = Color(0xFFFFF8F4)
val onSurfaceLight = Color(0xFF211A14)
val surfaceVariantLight = Color(0xFFF5DDD0)
val onSurfaceVariantLight = Color(0xFF52443C)
val outlineLight = Color(0xFF85746B)
val outlineVariantLight = Color(0xFFD8C2B8)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF382E28)
val inverseOnSurfaceLight = Color(0xFFFDEDE4)
val inversePrimaryLight = Color(0xFFFFB77E)
val surfaceDimLight = Color(0xFFE5D6CC)
val surfaceBrightLight = Color(0xFFFFF8F4)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF1E9)
val surfaceContainerLight = Color(0xFFFAEBE2)
val surfaceContainerHighLight = Color(0xFFF4E5DC)
val surfaceContainerHighestLight = Color(0xFFEEDFD7)

// Dark theme
val primaryDark = Color(0xFFFFB77E)
val onPrimaryDark = Color(0xFF4E2000)
val primaryContainerDark = Color(0xFF733600)
val onPrimaryContainerDark = Color(0xFFFFDCC2)
val secondaryDark = Color(0xFFE5C0A8)
val onSecondaryDark = Color(0xFF3E2318)
val secondaryContainerDark = Color(0xFF5C3E2E)
val onSecondaryContainerDark = Color(0xFFFFDCC8)
val tertiaryDark = Color(0xFFC7CA90)
val onTertiaryDark = Color(0xFF303314)
val tertiaryContainerDark = Color(0xFF474A2A)
val onTertiaryContainerDark = Color(0xFFE3E6AA)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1310)
val onBackgroundDark = Color(0xFFEEDFD7)
val surfaceDark = Color(0xFF1A1310)
val onSurfaceDark = Color(0xFFEEDFD7)
val surfaceVariantDark = Color(0xFF52443C)
val onSurfaceVariantDark = Color(0xFFD8C2B8)
val outlineDark = Color(0xFFA08D84)
val outlineVariantDark = Color(0xFF52443C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEEDFD7)
val inverseOnSurfaceDark = Color(0xFF382E28)
val inversePrimaryDark = Color(0xFFA05B15)
val surfaceDimDark = Color(0xFF1A1310)
val surfaceBrightDark = Color(0xFF423630)
val surfaceContainerLowestDark = Color(0xFF140E0B)
val surfaceContainerLowDark = Color(0xFF231B17)
val surfaceContainerDark = Color(0xFF271F1B)
val surfaceContainerHighDark = Color(0xFF322925)
val surfaceContainerHighestDark = Color(0xFF3D3430)
