package com.kado.app.data.local

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.migration.Migration
import androidx.sqlite.SQLiteConnection
import androidx.sqlite.execSQL
import com.kado.app.data.local.dao.BulkEditRuleDao
import com.kado.app.data.local.dao.CardDao
import com.kado.app.data.local.dao.CardStateDao
import com.kado.app.data.local.dao.DeckDao
import com.kado.app.data.local.dao.SettingsDao
import com.kado.app.data.local.entity.BulkEditRuleEntity
import com.kado.app.data.local.entity.CardEntity
import com.kado.app.data.local.entity.CardStateEntity
import com.kado.app.data.local.entity.DeckEntity
import com.kado.app.data.local.entity.SettingsEntity

val MIGRATION_1_2 = object : Migration(1, 2) {
    override fun migrate(connection: SQLiteConnection) {
        connection.execSQL(
            "CREATE TABLE IF NOT EXISTS `settings` (" +
                    "`id` INTEGER NOT NULL PRIMARY KEY, " +
                    "`themeMode` TEXT NOT NULL DEFAULT 'system', " +
                    "`cardFontScale` REAL NOT NULL DEFAULT 1.0, " +
                    "`appFontScale` REAL NOT NULL DEFAULT 1.0)"
        )
    }
}

val MIGRATION_2_3 = object : Migration(2, 3) {
    override fun migrate(connection: SQLiteConnection) {
        connection.execSQL("ALTER TABLE cards ADD COLUMN subDeckIndex INTEGER DEFAULT NULL")
        connection.execSQL("CREATE INDEX IF NOT EXISTS index_cards_deckId_subDeckIndex ON cards (deckId, subDeckIndex)")
    }
}

val MIGRATION_3_4 = object : Migration(3, 4) {
    override fun migrate(connection: SQLiteConnection) {
        connection.execSQL("ALTER TABLE settings ADD COLUMN language TEXT NOT NULL DEFAULT 'en'")
    }
}

val MIGRATION_4_5 = object : Migration(4, 5) {
    override fun migrate(connection: SQLiteConnection) {
        connection.execSQL(
            "CREATE TABLE IF NOT EXISTS `bulk_edit_rules` (" +
                    "`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, " +
                    "`name` TEXT NOT NULL, " +
                    "`frontFindPattern` TEXT NOT NULL, " +
                    "`frontReplacePattern` TEXT NOT NULL, " +
                    "`frontIsRegex` INTEGER NOT NULL DEFAULT 0, " +
                    "`frontEnabled` INTEGER NOT NULL DEFAULT 1, " +
                    "`backFindPattern` TEXT NOT NULL, " +
                    "`backReplacePattern` TEXT NOT NULL, " +
                    "`backIsRegex` INTEGER NOT NULL DEFAULT 0, " +
                    "`backEnabled` INTEGER NOT NULL DEFAULT 1, " +
                    "`createdAt` INTEGER NOT NULL)"
        )
    }
}

@Database(
    entities = [DeckEntity::class, CardEntity::class, CardStateEntity::class, SettingsEntity::class, BulkEditRuleEntity::class],
    version = 5,
    exportSchema = false
)
@ConstructedBy(KadoDatabaseConstructor::class)
abstract class KadoDatabase : RoomDatabase() {
    abstract fun deckDao(): DeckDao
    abstract fun cardDao(): CardDao
    abstract fun cardStateDao(): CardStateDao
    abstract fun settingsDao(): SettingsDao
    abstract fun bulkEditRuleDao(): BulkEditRuleDao
}

// The actual implementation is generated by Room's KSP processor
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object KadoDatabaseConstructor : RoomDatabaseConstructor<KadoDatabase>
